name: Auto Checkin Job

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-sign:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 手动缓存依赖
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # pip 默认缓存路径
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 生成 1 到 5 分钟的随机等待时间
      - name: Generate random wait time (1-5 minutes)
        id: random_wait
        run: |
          # 生成 1 到 5 之间的随机数（分钟）
          RANDOM_WAIT=$(( (RANDOM % 5) + 1 ))
          echo "随机等待时间: $RANDOM_WAIT 分钟"

          # 将分钟转换为秒
          WAIT_SECONDS=$((RANDOM_WAIT * 60))
          echo "等待时间: $WAIT_SECONDS 秒"

          # 等待到随机时间
          sleep $WAIT_SECONDS

      # 6. 运行脚本
      - name: Run auto checkin script
        id: run_script
        continue-on-error: true
        env:
          CONFIGS: ${{ secrets.CONFIGS }}
        run: |
          echo "任务在随机时间执行：$(date)"
          python main.py
